version: '3'

services:
  postgres:
    image: 'postgres:11-bullseye'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concurrency
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
  
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis/:/data
  
  mailing:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    